ruby/rake

doc/glossary.rdoc
This PR fixes some minor grammatical issues in the glossary.
=> Fix unclosed parens and other minor grammatical issues in glossary.rdoc

lib/rake/ext/string.rb
hello, everyone!
I write a long commit message, hope that's clear.
=> more readable `String#ext` method

doc/glossary.rdoc
=> fix: line longer than 78 chars.

doc/rakefile.rdoc
Support for this was removed on commit: 5148aac8b61246432d6d87f19f26e401ace62853
=> Remove doc section: Task Arguments and the Environment

.travis.yml
* Update CRuby 2.1 and CRuby 2.2, added CRuby 2.3.
* Added JRuby 9.0.x.0 and head
=> Update travis targets for CRuby and JRuby

README.rdoc, appveyor.yml
We need to build with windows environment continuously.
=> Enabled Appveyor build.

lib/rake/testtask.rb, test/test_rake_test_task.rb
Picked up from https://github.com/jimweirich/rake/pull/69
I will merge at Rake 11
=> Use ruby warnings by default

History.rdoc, lib/rake/cpu_counter.rb
=> Use IO#popen instead of Open3.popen3

lib/rake/linked_list.rb
- This PR incldues a number of small changes to make the API for the
LinkedList class both easier to read, easier to override and hopefully
easier to implement a subclass.
- Refactored a few methods to use Symbol#to_proc
- Added comments regarding implementation details so those who wish to
subclass can do so easily
=> LinkedList Refactor

lib/rake/testtask.rb, test/test_rake_test_task.rb
Another patch of https://github.com/ruby/rake/pull/118
=> Use -W2 instead of --verbose for JRuby

lib/rake/testtask.rb, test/test_rake_test_task.rb
Fixed https://github.com/ruby/rake/issues/139
=> Fix dependency task for Rake::TestTask

.travis.yml, test/helper.rb, test/test_private_reader.rb
Fix broken test wiht rubinius-3.x
=> Workaround for rubinius

lib/rake/file_utils.rb, test/test_rake_file_utils.rb
Fix https://github.com/ruby/rake/issues/201 problem if that is a bug.
=> Change FileUtils#sh to adopt with hash style option.

appveyor.yml
Maybe, Fixes https://github.com/ruby/rake/issues/255
=> To use gem install insteaad of bundle install

lib/rake/task.rb, test/test_rake_task.rb
Since I always fail to type `prerequisites`.
=> Add alias `prereqs`.

lib/rake/application.rb, lib/rake/file_creation_task.rb, lib/rake/file_list.rb, lib/rake/file_task.rb, lib/rake/file_utils.rb, lib/rake/promise.rb, lib/rake/scope.rb, lib/rake/task.rb
* remove trailing extension name
* remove space after `!` operator
=> Remove trailing extension name

lib/rake/application.rb
Fixed broken tests with https://bugs.ruby-lang.org/issues/15231
=> Fixed test fails caused by 2.6 warnings 

.rubocop.yml, test/helper.rb, test/test_rake_task.rb
This PR is just fixing a few issues that were being reported by Rubocop.
=> Fix outstanding rubocop warnings

rake.gemspec
=> Removed gitignore from gemspec files.

lib/rake/rake_test_loader.rb
Fixed https://github.com/ruby/rake/issues/388
=> Fixed the regression of #388

lib/rake/rake_test_loader.rb
Fixes https://github.com/ruby/rake/issues/388#issuecomment-876363229
=> Added Rake namespace explicitly

CONTRIBUTING.rdoc
=> docs: update CONTRIBUTING.rdoc

README.rdoc
Also shows the current maintainer(s) to wider community contributors.
=> Add credit for maintenance in Rake 12/13

.github/workflows/test.yml, rake.gemspec
Related with https://github.com/ruby/setup-ruby/issues/493
=> Drop to support ruby 2 2

test/test_rake_file_utils.rb
Same as https://github.com/rubygems/rubygems/pull/7370
=> Removed redundant block

rake.gemspec
Since you seem to have switched.
=> Switch changelog_uri to releases tab

README.rdoc
... as per this https://github.com/ruby/rake/pull/66#issuecomment-2390720612 on  @jahio's original PR :pray:
=> Link to Jim's last `rake` commit (not the git tree with that SHA)

test/test_rake_rake_test_loader.rb
https://github.com/ruby/rake/actions/runs/17037593837/job/48293620256?pr=652
=> Fixed assertion result with the latest stable version of JRuby

test/test_rake_rake_test_loader.rb
For https://github.com/ruby/rake/pull/656
=> Fixup `test_load_error_raised_implicitly` with JRuby
