- lib/rake/task_manager.rb
TaskManager already has a private declaration in line 215.
> Remove an unneeded private declaration

- .travis.yml
--no-rdoc and --no-ri option is deprecated.
Please see [gem install(command reference)](http://guides.rubygems.org/command-reference/#gem-install).
> Use --no-document option instead of --no-rdoc and --no-ri option

- CONTRIBUTING.rdoc
I changed CD to `cd` (enclosed by `+`) in CONTRIBUTING.rdoc.
I guess CD in CONTRIBUTING.rdoc is supposed to mean a linux `cd` command, but if it is written in uppercase, it might be confusing because it is normally written in lowercase(http://www.linfo.org/cd.html).
It is a subtle change but to make it a little bit easier to understand.
> Improve markup by modifying a linux command of 'CD' into lowercase 'cd' (enclosed by '+')

- doc/rake.1
Reverts ruby/rake#24
It removed "rake 10.3.2" and "Rake User Commands" sections.
> Revert "Convert manual page to use semantic -mdoc macros."

- lib/rake/ext/time.rb
This kind of monkey patching isn't really necessary since `Time#<=>` is smart enough to try inverting the operands if the argument it receives is not an instance of Time.
Also the alias chain can be a source of headaches if you want to use it simultaneously with the new method `Module#prepend`: https://github.com/rails/rails/pull/19878/#issuecomment-106851263
> Remove unnecessary monkey patching

- CONTRIBUTING.rdoc
@hsbt _et al._ - I'm submitting a minor "documentation fix" for the `CONTRIBUTING.rdoc` file, which didn't include instructions for installing the `"hoe"` gem dependency.
It's a bit off-putting for newbies to follow the instructions, only to get the following error message when running `rake newb` in a Ruby environment in which the `"hoe"` gem hasn't been previously installed:
```shell
$ rake newb
rake aborted!
LoadError: cannot load such file -- hoe
/Users/pvdb/Workarea/pvdb/rake/Rakefile:18:in `<top (required)>'
(See full trace by running task with --trace)
$_
```
> Fix contributing documentation: install "hoe" gem dependency

- lib/rake/clean.rb
@hsbt _et al._ - another minor "documentation fix" in this PR, one that makes the description of the `"clobber"` task consistent with the description of the `"clean"` task, as they use singular/plural nouns inconsistently at the moment.
**before:**
```shell
$ rake -T | egrep '^rake (clean|clobber)'
rake clean    # Remove any temporary products
rake clobber  # Remove any generated file
$ _
```
**after:**
```shell
$ rake -T | egrep '^rake (clean|clobber)'
rake clean    # Remove any temporary products
rake clobber  # Remove any generated files
$ _
```
Some diehards might argue that "any" should only be used in conjunction with uncountable nouns, and then only in questions or negative sentences, making these task descriptions grammatically incorrect, but at least with this PR they are …
> Pluralize (for consistency)

- lib/rake/task_manager.rb
- test/test_rake_task.rb
- test/test_rake_task_manager.rb
Addresses issue #22. Makes it a bit easier for new users to get started by pointing them at the `--task` parameter if they e.g. run rake with no arguments in a project with no default task.
> More helpful error message for unknown tasks.

- doc/rake.1
- lib/rake/file_list.rb
- test/test_rake_file_list.rb
Hi,
there is a little issue with the FileList SPECIAL_RETURNs:
```
class CustomFileList < Rake::FileList
end
c = CustomFileList.new #=> []
c.class #=> CustomFileList
c.uniq.class #=> Rake::FileList but should be a CustomFileList
```
What do you think about this fix?
> Fix special_return method's result wrapping to be more dynamic

- lib/rake/task.rb
- test/test_rake_task.rb
Picked up from https://github.com/jimweirich/rake/pull/264
/cc @svanderbleek
I prepare to release Rake 11 and will merge this pull request.
> Lookup prerequisites with same name outside of scope instead of matching self

- lib/rake/task.rb
- test/test_rake_task.rb
It's useful to check if a Rake::Task has already been run/invoked, so
let's make this information accessible.
My use case:  I have a rake task which invokes Rails' `environment` rake task with a specific configuration so I want to raise an error if `environment` was previously run/invoked or else my rake task will become a no-op.  I'd rather not have to do this:
```ruby
raise 'xxx' if Rake::Task['environment'].instance_variable_get(:@already_invoked)`
```
> Make Rake::Task already_invoked publicly accessible.

- README.rdoc
This is just a friendly (albeit somber) pull request to acknowledge Jim Weirich in a more salient, respectful way. The original copyright statement under "other stuff", regardless of who put it there, now seems almost disrespectful, as if he's an afterthought and nothing more.
It's important that we acknowledge and thank innovators for their work, even in death; such ongoing acknowledgement shows veterans and newcomers alike that building great things leaves a lasting legacy; seeing that legacy can inspire others to build *their own* legacy by contributing to the community.
More functionally, newcomers to Ruby might see lots of references to Jim and jimweirich/rake as the repository location (e.g. books, old articles/blog posts, etc.), so this may clear up some confusion.
Merely a …
> Historical info on Jim, acknowledgement and thanks

- lib/rake/file_list.rb
- test/test_rake_file_list_path_map.rb
`String#pathmap` accepts a block to perform replacements but `FileList#pathmap` ignores the block given.
This is to make FileList accept and pass the block to the String method.
> Make FileList#pathmap behave like String#pathmap

- lib/rake/task_arguments.rb
- test/test_rake_task_arguments.rb
This change allows TaskArguments to respond to fetch in the same way that a hash would.  I ran into this scenario where I was trying to pass the args for a rake task directly into a class constructor.  Calling args.fetch in that case results in nil values being returned.  This was confusing at first because when the TaskArguments object is 'puts' or inspected, it returns what looks like a hash.  It wasn't until I checked the class of the args that I realized the discrepancy.  This change helps eliminate that confusion and would allow the arguments to be passed in directly.
I'm not sure if this is the right approach or if you should just call `to_hash` on the args (which is what I ended up doing).  Any feedback would be great.  Thanks!
> Add fetch to task arguments.

- lib/rake/testtask.rb
- test/test_rake_test_task.rb
`rake test —verbose` did not result in verbose mode for MiniTest.
The verbose option needs to be forwarded to the Ruby call.
Missing tests are added.
> Fix TestTask verbose

- .travis.yml
travis(rvm) added deprecated option named `cext.enabled`. It shows warning message with JRuby 9.0.0.0. I eliminates it.
> ignored deprecated options with JRuby

- lib/rake/file_list.rb
Hi there,
this is a follow up of #74.
Some of file list's methods returning a new FileList instance are not returning the expected type of objects in case of inheritance from FileList. I fixed this in the mentioned PR but forgot to fix this for all methods. I apologise  for the inconvenience.
Please let me know if I should add extra tests for this. Currently I rely on the existing tests.
> Replace file lists internal calls to `new` by a more generic `self.class.new`

- lib/rake/application.rb
@hsbt _et al._ - a minor change to `lib/rake/application.rb` which tried to declare the `FIXNUM_MAX` constant as `private`, which isn't possible in Ruby... I've replaced the `private` method call with an annotation similar to the `internal` annotation on [line 144 of that same file][one_four_four], to at least express the intent.
[one_four_four]: https://github.com/ruby/rake/blob/master/lib/rake/application.rb#L144
> Mark the FIXNUM_MAX constant as private with an annotation

- lib/rake/file_list.rb
- test/test_rake_file_list.rb
This PR changes FileList so that `a_filelist.exclude(something)` is more consistent with `a_filelist.exclude(*FileList[something])`.
Now `FileList#exclude` can accept curly brace patterns, like `"{foo,bar}.rb"`, the same way `FileList#include` does.
And it now also accepts arrays, or array-like things, excluding each element of that array.
> Make FileList#exclude more analogous to FileList#include

- lib/rake/trace_output.rb
- test/test_rake_application.rb
TraceOutput#trace_on has a bug that causes the matching to fail if a string is incorrectly encoded - for example encoded as 'US-ASCII' but contains unicode characters. This causes a new exception to be thrown, losing the stack trace of the previous exception.
This can occur, for example, in Ruby 1.9 when one of the dependencies of a project includes a file that contains unicode but does not specify an encoding (as the default for Ruby 1.9 is US-ASCII). 
This was the case in a certain version of the Puma web server, which was fixed in https://github.com/puma/puma/pull/924 but was very difficult to debug  due to the incorrect stack trace provided by rake.
> Correctly handle bad encoding in exception messages

- lib/rake/testtask.rb
- test/test_rake_test_task.rb
This PR allows to specify dependencies(prerequisites) for test task
```ruby
Rake::TestTask.new do |t|
t.deps = :setup
end
```
> Add possibility to specify test task prerequisites

- History.rdoc
- lib/rake/testtask.rb
- test/test_rake_test_task.rb
It's unexpected change from Rake 10. Fixes https://github.com/ruby/rake/issues/125
> Remove -W option on TestTask

- lib/rake/application.rb
- lib/rake/rake_test_loader.rb
- lib/rake/rule_recursion_overflow_error.rb
- lib/rake/thread_pool.rb
* shellwords is not use in Rake 11
* thread is already core library. Not necessary for using it
> Removed needless requires

- lib/rake/task.rb
- test/test_rake_task.rb
Closes https://github.com/ruby/rake/issues/106. Also makes `first_sentence` lookout for exclamation marks. For example:
```
desc "This drops your database! Make sure you've backed up your db."
```
Running `rake -T` will show
`rake testing            # This drops your database`
> Update comment parsing rules

- lib/rake/file_utils.rb
- test/test_rake_file_utils.rb
This allows any spawn option to be used with `sh`.
This also improves the printed command output when an ENV hash is supplied.
> Spawn options for sh

- lib/rake/task_arguments.rb
- test/test_rake_task_arguments.rb
I want to change the action of named arguments #with_defaults.
followings are example.
```
task :some_task => [:a, :b] do |task, args|
args.with_defaults({a: 'a', b: 'b'})
p args.to_hash
end
rake some_task[,c]  # => {:a=>"", :b=>"c"}
rake some_task[,c]  # =>  {:a=>"a", :b=>"c"}
```
Rake::TaskArguments are separated by comma, so when I want default value for `:a` but specify for `:b`, want to use arguments `[,any]`.
Please let me know if any problems, I will fix my code and resend pull request.
> Don't set if args are blank

- lib/rake/multi_task.rb
- test/test_rake_multi_task.rb
If tasks A and B both depend on C, they race to grab the invocation
lock on C. If A wins, it sets @already_invoked and executes C while
holding the lock. When C completes, A releases the lock, B acquires it
and immediately returns since C is @already_invoked. Unfortunately,
this does not distinguish failed execution of C. Instead, if executing
C raises an exception for A, we want to raise the same exception in B
so it is aborted.
> Do not run tasks when their prerequisites fail

- doc/rakefile.rdoc
Related to commit 57cdf0fafb85c9f4efbcd871e094686fdc2ca753.
Support for environment variables as task argument was removed on
commit 5148aac8b61246432d6d87f19f26e401ace62853.
> Remove mention of environment variables as task argument.

- README.rdoc
Otherwise:
Note the trailing slash not being part of the link nor the label.
I couldn't help myself not to see this 😄
> Remove trailing slash on a link in README

- doc/rake.1
@hsbt re #24 and #63. This re‐adds the “rake 10.4.2” section. I don’t see a way to re‐add “Rake User Commands”; is it really necessary?
> Convert manual page to use semantic -mdoc macros.

- .travis.yml
- test/helper.rb
- test/test_private_reader.rb
I will not support rubinius specification changes on rake.
https://travis-ci.org/ruby/rake/jobs/148028335
https://travis-ci.org/ruby/rake/jobs/148028336
> Drop to rubinius support 

- lib/rake/testtask.rb
- test/support/rakefile_definitions.rb
- test/test_rake_functional.rb
CASE
Originally, Jim Weirich developed Rake to work with (arguably) `Test::Unit`, before the arrival of `Minitest`. And none of the following gems:
* `Cucumber`
* `RSpec`
* `Test::Unit`
(used for testing) prompts the user to rerun their tests with a `--verbose` command line option.
`Minitest` (somewhat newer) does so prompt the user—it (sometimes) emits the message: "You have skipped tests. Run with `--verbose` for details." Under Rake, this message is somewhat confusing. This has been reported (see below).
Rake's own test suite employs `Minitest`. When tests are skipped (as on `Windows`), it also displays this problem (i.e., `Minitest` emits the above, confusing message).
In a Rails issue, [Adding --verbose flag to rake test doesn't do …
> TestTask when --verbose prompts for TESTOPTS="--verbose"

- lib/rake/task.rb
- test/test_rake_task.rb
> #156 Remove arguments on clear

- .travis.yml
- Rakefile
- appveyor.yml
bundler-1.13.0 references `Gem::Source`. It is only provided from rubygems-2.6.x
> Fix test fail caused by bundler-1.13.x

- lib/rake/testtask.rb
When using Rake::TestTask with a lot of files at once, sometimes the failure output from rake is quite overwhelming (because of the file list appended to the message "Command failed with status..."). This commit only shows that extended information if the user asks for verbose output in the Rake::TestTask or uses the --trace command when invoking rake.
> show extended output on testtask fail only with verbose or trace

- test/test_rake_application.rb
- test/test_rake_functional.rb
ref. https://travis-ci.org/ruby/rake/jobs/163951069
It caused by `Dir.chdir` specification on JRuby
> skip tests with JRuby 9k. 

- lib/rake/clean.rb
- test/test_rake_clean.rb
I had to hack FileUtils a little to get the test suite to pass.
I'm wondering if this should be a bug reported upstream.
> Respect trace option in cleanup

- lib/rake/file_utils.rb
As of #138, the `OPT_TABLE` entries for `sh` and `ruby` are no longer used internally, and a GitHub search for these entries suggests that they are not used externally: https://git.io/v6hpi
> remove obsolete OPT_TABLE entries

- lib/rake/task_arguments.rb
- test/test_rake_application.rb
- test/test_rake_functional.rb
- test/test_rake_task_arguments.rb
TaskArguments#to_hash is return @hash object.
The method should be return duplicated object like a "to_a".
> fix to_hash bug

- lib/rake/task_arguments.rb
- test/test_rake_task_arguments.rb
`ta = Rake::TaskArguments.new([:a, :b, :c], [1, 2, 3])`
`puts ta # {:a=>1, :b=>2, :c=>3}`
`puts ta # #<Rake::TaskArguments a: 1, b: 2, c: 3>`
The current implementation leads one to believe they are working with a hash. This can lead to some confusion if you try doing something like `ta.a = 'one'` which will silently ignore the assignment.
In addition, I think `def_method` is preferable to `method_missing` to create accessors. That way `ta.a = 'one'` would generate a `NoMethodError`. Thoughts?
Shoutout to @eric-hu, with whom I discovered this issue.
> Represent a TaskArgument object such that it's not confused with a hash.

- lib/rake/task.rb
- test/test_rake_task_with_arguments.rb
Consider this task:
```ruby
task :t, [:arg] do |task, arg: 'default_value'|
emotion = "\e[32m^_^\e[0m"
emotion = "\e[31mt.t\e[0m" if ARGV[0] =~ /t\[(.*)\]$/ && $1 != arg
puts "task #{task.name.inspect} got #{arg.inspect} #{emotion}"
end
```
Run this on your machine right now and you'll see the task is in tears. But this commit turns tearful eyes into smiling ones, observe:
```sh
$ rake t
task "t" got "default_value" ^_^
$ rake t[custom_value]
task "t" got "default_value" t.t
$ ruby -Ilib exe/rake t
task "t" got "default_value" ^_^
$ ruby -Ilib exe/rake t[custom_value]
task "t" got "custom_value" ^_^
```
It accomplishes this by always invoking the action in the same way. [Previously](https://github.com/ruby/rake/blob/59856100815b841624269f817c815f54921bf321/lib/rake/task.rb#L251-L256), …
> Actions adore keyword arguments

- lib/rake/task_arguments.rb
- test/test_rake_task_arguments.rb
This PR adds `Rake::TaskArguments#key?(key)` as an alias of `has_key?(key)`.
---
`Rake::TaskArguments` exposes a Hash-like interface including `#has_key?(key)`, but is missing `#key?(key)`. Making this worse, the `method_missing` behaviour means `args.key?(:foo)` does not raise NoMethodError, instead treating it like `args[:key?]` and generally returning `nil`.
The commonly referenced [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide#hash-key) says:
> Use `Hash#key?` instead of `Hash#has_key?` … As noted [here](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/43765) by Matz, the longer forms are considered deprecated.
which links to matz saying:
> "has_key" has already been deprecated by "key?"
[RuboCop](https://github.com/bbatsov/rubocop)'s …
> Rake::TaskArguments#key? alias of #has_key?

- doc/rakefile.rdoc
I removed `traken` words in `rakefile.rdoc` because it is probably typo.
> Fixes documentation typo in rakefile.rdoc

- .travis.yml
This PR adds 2.4.0 as a test target in Travis.
It also takes the patch versions of other rubies from the `ruby-install --latest` output and updates them.
> Travis: add 2.4.0 to matrix, update patch versions

- test/test_rake_application.rb
As the result of https://bugs.ruby-lang.org/issues/13043, now `Exception#cause` should not have a loop.
In the example https://github.com/jimweirich/rake/issues/272, the code doesn't seem to intend the loop itself but just re-raising the first exception instead of the next exception.  Therefore I consider the last assertion superfluous.
> Remove an extra assertion

- lib/rake/file_task.rb
- test/support/rakefile_definitions.rb
- test/test_rake_functional.rb
This fixes #92 what says below:
> The problem seems to stem from the fact that the internal function `out_of_date?` (in `file_task.rb`) does not take into account when a file should have updated its timestamp (but didn't, because this is a dry-run).
I think so. In this Pull Request, `FileTask#out_of_date?` calls dependency `FileTask`'s `#out_of_date?` via `FileTask#needed?`.
> FileTask#out_of_date? calls depended FileTask#out_of_date? for execution

- lib/rake/task_manager.rb
- test/test_rake_rules.rb
rules such as 
``` ruby
rule ".min.js" => ".js" do |t|
end
```
didn't work because Rake would simple replace the js part of".min.js" with ".js", creating a cyclic dependency. This PR makes rules like this work by always making sure the whole target pattern of is replaced, rather than just the very final extension. 
All tests green. A test for the new feature added.
> Chained extensions

- lib/rake/rake_test_loader.rb
- test/test_rake_rake_test_loader.rb
When you attempt to run tests on a nonexistent file the error can be buried (see #194).  This change adds some whitespace and removes the backtrace to make the error more visible.
```
$ rake test TEST=no_such_file
/usr/local/bin/ruby -w -I"lib:test" -I"/Users/erichodel/Work/git/rake/lib" "/Users/erichodel/Work/git/rake/lib/rake/rake_test_loader.rb" "no_such_file" 
cannot load such file -- /Users/erichodel/Work/git/rake/no_such_file
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/Users/erichodel/Work/git/rake/lib" "/Users/erichodel/Work/git/rake/lib/rake/rake_test_loader.rb" "no_such_file" ]
Tasks: TOP => test
(See full trace by running task with --trace)
```
> Make LoadError from running tests more obvious

- .travis.yml
[JRuby 9.1.10.0 has been released](http://jruby.org/2017/05/25/jruby-9-1-10-0.html), but there is not in list of ["Travis CI: Precompiled Ruby Versions"](http://rubies.travis-ci.org/). So I added `jruby-9.1.9.0` what is in the list now.
> Update to latest versions of Ruby 2.2, 2.3 and JRuby 9k

- appveyor.yml
AppVeyor [supports Ruby 2.4.1-1](https://www.appveyor.com/updates/2017/06/12/) with RubyInstaller2 ([discussed on a GitHub issue](https://github.com/appveyor/ci/issues/1350)). It's listed on [Build Environment page of AppVeyor](https://www.appveyor.com/docs/build-environment/#ruby).
> Add ruby_version 24 and 24-x64 to appveyor.yml

- lib/rake/task_manager.rb
This fixes the
NoMethodError: undefined method `match' for nil:NilClass
error with gettext/gettext_i18n_rails.
https://github.com/ManageIQ/manageiq/issues/4774
> When pattern is nil, enhance_with_matching_rule will not fail

- rake.gemspec
This PR makes the gemspec exclude 3 configuration files from the repository's root directory.
The problem that this change solves for me is that a Rake-task-based RuboCop
configuration-file finding method can run into these RuboCop rules, when they
are in a searched filesystem path.
(Another issue: The rules for this project currently present warnings when run with RuboCop 0.49.1.)
The warnings:
<details>
```
/Users/olle/opensource/rake/.rubocop.yml: Style/LineLength has the wrong namespace - should be Metrics
/Users/olle/opensource/rake/.rubocop.yml: Style/IndentationWidth has the wrong namespace - should be Layout
/Users/olle/opensource/rake/.rubocop.yml: Style/Tab has the wrong namespace - should be Layout
/Users/olle/opensource/rake/.rubocop.yml: Style/EmptyLines has the wrong …
```
> gemspec: Exclude various YAML configuration files

- .rubocop.yml
- rake.gemspec
- test/helper.rb
- test/test_rake_file_utils.rb
- test/test_rake_rake_test_loader.rb
- test/test_rake_rules.rb
ref. https://github.com/ruby/rake/pull/217
> Fixup rubocop warnings

- lib/rake/task_manager.rb
- test/test_rake_task.rb
This is a follow up of an [older PR](https://github.com/ruby/rake/pull/29/files) that added a better message for invalid rake task names. The proposed change uses did you mean in order make a rake task suggestion in addition to the default error message.
> Added did you mean to rake

- lib/rake/application.rb
- lib/rake/rake_module.rb
- test/test_rake_application.rb
- test/test_rake_application_options.rb
- test/test_rake_task.rb
- test/test_rake_task_argument_parsing.rb
- test/test_rake_win32.rb
I want to be able to load a set of rake tasks from within another application.  Doing this presently is difficult, and looks something like this:
```ruby
Dir.chdir 'other/dir'
rake = Rake::Application.new
Rake.application = rake
rake.options.trace = true
rake.options.backtrace = true
rake.options.rakelib = %w[rakelib]
rake.load_rakefile
puts rake.tasks
```
Figuring out which options you need to set is hard (and not documented), figuring out you need to set `Rake.application` is not documented, and the process of getting your Rakefile loaded is not documented.
This PR replaces the above with a much simpler option:
```ruby
Dir.chdir 'other/dir'
rake = Rake.with_application do |rake|
rake.load_rakefile
end
puts rake.tasks
```
Figuring out which options is now hidden from the user.
There are …
> Make rake easier to use as a library

- test/test_rake_task.rb
```
test/test_rake_task.rb:467: warning: ambiguous first argument; put parentheses or a space even after `/' operator
test/test_rake_task.rb:470: warning: ambiguous first argument; put parentheses or a space even after `/' operator
```
> fixed warnings

- lib/rake/file_list.rb
- test/test_rake_file_list.rb
I believe calling `existing` on a FileList should return a unique list because files in a directory are unique. This could also solve issue #30 and #225 if he calls each on the existing FileList.
> Account for a file that match 2 or more patterns.

- lib/rake/file_task.rb
FileTask#out_of_date? has been changed in 462e403a to call #needed?
which calls #out_of_date? recursively. In some cases, where the
graph of dependencies is fairly dense, this leads to quadratic
performance when it was linear before.
Use #all_prerequisite_tasks to avoid the problem. This also saves
a File.exist? test as #timestamp already takes it into account.
> fix quadratic performance in FileTask#out_of_date?

- lib/rake/application.rb
- test/test_rake_application.rb
Since v10.2.0, if an exception has a nested cause exception, [the cause is also displayed in the trace output](https://github.com/ruby/rake/commit/fbb22e7f570fc573ad1bff9d5905df1ab1cbd475).
For deeply-nested exceptions, this output can be quite lengthy - for example, Rails migrations nest DB errors twice over, resulting in an error message and backtrace repeated three times. With long backtraces, this output can be difficult to visually scan.
To break up the output and make it clearer what each individual backtrace relates to, this PR adds whitespace and a "Caused by:" label to each nested exception being displayed.
Given the following `Rakefile`:
```ruby
task :oops do
begin
raise StandardError, "oops"
rescue => a
begin
raise ArgumentError, "didn't like that", cause: a
rescue => b
raise …
```
> Clarify output when printing nested exception traces

- rake.gemspec
- as suggested by @hsbt in issue #230 on github
- problems with 1.9.3 have been reported, which is long EOL'd
> update required_ruby_version to 2.0.0

- README.rdoc
It seems the ftp related tasks are now provided by the rake-contrib gem.
Fixes #238.
> Add missing information on FTP publishing to README

- appveyor.yml
AppVeyor says
```
gem install bundler --no-document
bundler's executable "bundle" conflicts with C:/Ruby200/bin/bundle
Overwrite the executable? [yN]
```
and it [timed out upon elapsing 1 hour](https://ci.appveyor.com/project/aycabta/rake/build/1.0.12). This commit adds `-f` option for it.
> Force installation Bundler

- README.rdoc
According to rake.gemspec, rake requires at least ruby 2.0.0
https://github.com/ruby/rake/blob/f35ce833db6976fcad0f9315689098cdb8e6d833/rake.gemspec#L33
> [skip ci] Fix minimal ruby version on README

- lib/rake/rake_test_loader.rb
- test/test_rake_rake_test_loader.rb
> Re-raise a LoadError that didn't come from require in the test loader

- rake.gemspec
Hi there :wave:
I noticed that in [this commit](https://github.com/ruby/rake/commit/6258ad54fcac8916394cc49ee306d1fd7aa05ca8) you bumped the version but did not change the `date` field in the `rake.gemspec`. This means that on rubygems.org, Rake 12.2.1 and Rake 12.3.0 were seemingly released on the same day, but the commits show a different history. (The last released date was [this commit](https://github.com/ruby/rake/commit/e7ea2d15890c4b204f5fc558f5a7c65384abf586) but it has since been bumped on master with [this commit](https://github.com/ruby/rake/commit/0c4aab882547bdd14b3dfde93e0bb02ad26ff088).
May I suggest removing the `date` field from the `gemspec`? This way, RubyGems.org will automatically assign the current date to the package's release _and_ it means that you as a maintainer …
> Remove date field from rake.gemspec

- test/test_rake_file_creation_task.rb
- test/test_rake_multi_task.rb
`Rake::DSL` is already included in `Rake::TestCase`
> Removes duplicated inclusion of Rake::DSL

- lib/rake/application.rb
- test/test_rake_task_argument_parsing.rb
Fixes #260
Given a task that just inspect task arguments...
Current rake behavior
```
$ bundle exec rake "inspect_args[  one  ,  two  ,  three  ]"
"  one"
"two"
"three"
```
With this PR changes
```
$ bundle exec rake "inspect_args[  one  ,  two  ,  three  ]"
"one"
"two"
"three"
```
> [Fixes #260] Make space trimming consistent for all task arguments

- lib/rake/multi_task.rb
- lib/rake/task.rb
- test/test_rake_multi_task.rb
> [Fixes #189] [Fixes #190] Don't run task if it depends on already invoked but failed task

- lib/rake/task_manager.rb
did_you_mean  v1.2.0 has a breaking change to its formatter api:
https://github.com/yuki24/did_you_mean/compare/v1.1.2...v1.2.0
This PR uses the new `DidYouMean.formatter`, keeping backward compatibility for did_you_mean pre-1.2.0.
> support did_you_mean >= v1.2.0 which has a breaking change on formatters

- lib/rake/cpu_counter.rb
`Java::Java` is no longer defined by default, it's not defined until it is accessed:
```
$ jruby -e 'p defined?(Java::Java)'
nil
$ jruby -e 'p Java::Java'
Java::Java
```
In earlier JRuby versions, `defined?(Java::Java)` returned `"constant"`.
While this doesn't cause an test failures, it does result in the following warning when run on non-Windows systems: `!!!! Missing jruby-win32ole gem: jruby -S gem install jruby-win32ole`, because the first fallback code is to try to load `win32ole`, and on JRuby that prints the warning.
> Fix JRuby detection on JRuby 9.2 in cpu_counter.rb

- lib/rake/packagetask.rb
There is currently a couple of errors in rubocop that this PR is fixing:
```
❯ rubocop
Inspecting 97 files
...........................................................E.....................................
Offenses:
lib/rake/packagetask.rb:135:32: E: Lint/Syntax: unexpected token kDO_BLOCK
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
chdir(package_dir) do
^^
lib/rake/packagetask.rb:146:30: E: Lint/Syntax: unexpected token kDO_BLOCK
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
chdir(package_dir) do
^^
lib/rake/packagetask.rb:209:3: E: Lint/Syntax: unexpected token kEND
(Using Ruby 2.3 parser; configure using TargetRubyVersion parameter, under AllCops)
end
^^^
97 files inspected, 3 offenses detected
```
> fix errors in rubocop

- CONTRIBUTING.rdoc
I'm sorry for opening so many PRs today 😅 
This PR adds a section to `CONTRIBUTING.rdoc` on how to run Rubocop on the local machine.
> add rubocop section to CONTRIBUTING.rdoc

- lib/rake/task_manager.rb
- test/test_rake_task.rb
- test/test_rake_task_manager.rb
This PR is reworking the error message when a given task does not exist.
```
$ rake foo
rake aborted!
Don't know how to build task 'foo' (see --tasks)
/Users/colby/.gem/ruby/2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```
There is a good opportunity here to reword the `(see --tasks)` into something more meaningful and direct.
Users may not be aware of the `rake --tasks` option, so this PR adjusts the error message to instead be direct in saying that you can see a list of available tasks using this command. 
I've turned it into this, which i think provides better communication to users:
```
Don't know how to build task 'foo' (See the list of available tasks with `rake --tasks`)
```
> Rework the error message that tells users to list the tasks with `rake --tasks`

- .travis.yml
This PR is just updating the version of JRuby used in travis-ci to the latest version.
> update latest jruby version in travis

- README.rdoc
There is a set of resources listed in the README that's suppose to be linking to pages in the repo but isn't. The resources are:
Looking into this, i did stumble across https://github.com/ruby/rake/pull/6 to fix this issue but was declined. But IMO this should be fixed so that people can be correctly linked to the listed resources on Github.
> fix links to rake resources not showing on Github

- lib/rake/task.rb
Thread context switches are expensive, iterating through promises in reverse minimizes them.
See my blog post about it here: https://medium.com/@sanmiguelje/optimizing-rake-multitask-fece36a16c8f
> Improve multitask performance

- .travis.yml
- test/helper.rb
This is to prevent multiple travis-ci jobs running coveralls and results in the coveralls posting multiple reports per PR.
See:
- https://github.com/ruby/rake/pull/288
- https://github.com/ruby/rake/pull/283
> run coveralls only when COVERALLS env var is present

- CONTRIBUTING.rdoc
This PR is adjusting a couple of things:
Improve the instructions around running Rake's test suite. I think the instructions may have been left-over from a previous form and wasn't making a huge amount of sense. 
The second is denoting commands with the `$` prefix. This is a typical convention in documentation and helpful for new contributors.
> Improve running test instructions and denote commands with `$`

- CONTRIBUTING.rdoc
This is a bit nitpicky -  so feel free to close this. This PR is updating the URL for the public repository in the rake documentation to use `https` instead because security & privacy are 👍
> Update public clone URL to use https

- .travis.yml
This PR adds Ruby 2.6 to Travis-CI.
Note that We have to manually update RubyGems because Travis forces each ruby
version to have an old version of RubyGems, which breaks our tests in 2.6.
> Add ruby 2.6.0 to .travis.yml

- lib/rake/task_manager.rb
- test/test_rake_task_manager.rb
`Rake.application` can be initialized with a custom name, so use that in the error message when a task is not found in the index. The default application name is `rake`.
Amends #287
> Use the application's name in error message if a task is not found

- lib/rake/packagetask.rb
- test/test_rake_package_task.rb
```
$ unzip -l pkg/my_browser_extension-1.0.1.zip
Archive:  pkg/my_browser_extension-1.0.1.zip
Length      Date    Time    Name
---------  ---------- -----   ----
469  04-17-2019 17:02   manifest.json
0  04-19-2019 17:57   src/
1417  04-19-2019 11:55   src/main.js
0  04-19-2019 17:57   src/icons/
1946  04-17-2019 12:28   src/icons/48.png
5262  04-17-2019 12:29   src/icons/128.png
625  04-17-2019 12:28   src/icons/16.png
---------                     -------
9719                     7 files
```
```
$ unzip -l pkg/my_browser_extension-1.0.1.zip
Archive:  pkg/my_browser_extension-1.0.1.zip
Length      Date    Time    Name
---------  ---------- -----   ----
0  04-19-2019 17:57   my_browser_extension-1.0.1/
469  04-17-2019 17:02   my_browser_extension-1.0.1/manifest.json
0  04-19-2019 17:57 …
```
> Make `PackageTask` be able to omit parent directory while packing files

- lib/rake/task.rb
- lib/rake/task_manager.rb
- test/test_rake_task_manager_argument_resolution.rb
- test/test_rake_test_task.rb
Like [Makefile](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html).
> Add order only dependency.

- lib/rake/clean.rb
- lib/rake/file_utils.rb
- lib/rake/file_utils_ext.rb
- lib/rake/task.rb
- test/test_rake_file_utils.rb
Follows recent changes on keyword arguments in ruby 2.7.
> Update keyword args

- rake.gemspec
- test/test_rake_application.rb
- test/test_rake_backtrace.rb
- test/test_rake_file_list.rb
- test/test_rake_task_with_arguments.rb
It doesn't seem working with ruby 2.1 already.
```
$ ruby2.1 -I./lib exe/rake 
/opt/local/bin/ruby2.1 -w -I"lib:test"  "/Users/nobu/src/ruby/rake/lib/rake/rake_test_loader.rb" "test/test_private_reader.rb" "test/test_rake.rb" "test/test_rake_application.rb" "test/test_rake_application_options.rb" "test/test_rake_backtrace.rb" "test/test_rake_clean.rb" "test/test_rake_cpu_counter.rb" "test/test_rake_definitions.rb" "test/test_rake_directory_task.rb" "test/test_rake_dsl.rb" "test/test_rake_early_time.rb" "test/test_rake_extension.rb" "test/test_rake_file_creation_task.rb" "test/test_rake_file_list.rb" "test/test_rake_file_list_path_map.rb" "test/test_rake_file_task.rb" "test/test_rake_file_utils.rb" "test/test_rake_functional.rb" "test/test_rake_invocation_chain.rb" …
```
> Drop old ruby versions which are no longer tested

- rake.gemspec
Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/rake and be available via the rubygems API after the next release.
> Add project metadata to the gemspec

- test/test_rake_file_list.rb
Ruby 2.7 is deprecating taint, and taint will no longer have an
effect. See https://bugs.ruby-lang.org/issues/16131.
This just skips the test for FileList#clone and #dup copying the
taint flag on Ruby 2.7+.
> Skip a taint test on Ruby 2.7

- lib/rake/task_manager.rb
- test/test_rake_task_manager_argument_resolution.rb
I created addition some additional assertions in `test_good_arg_patterns` in advance of some changes I'm considering for `TaskManager#resolve_args`.  During that case, I found a case that returned unexpected results.  This pull contains the fix for that failing test case.
I updated some comments which didn't get updated in #269.
> Fix an incorrectly resolved arg pattern

- lib/rake/task.rb
- test/test_rake_task.rb
After a task is `reenable`d an exception of the pre-`reenable` invocation should not be raised but is.
> Fixed bug: Reenabled task raises previous exception on second invokation

- .github/workflows/macos.yml
- .github/workflows/ubuntu-rvm.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- test/test_rake_clean.rb
* See https://github.com/oracle/truffleruby/issues/1739
and f19222ffae9168d4c4d2867f14de06df89febad2.
cc @hsbt
> Test Rake on TruffleRuby

- rake.gemspec
I have not tested this change, I have just edited the file via GH, but the point is that currently, the `.github` directory is included in released gem, which is probably mistake.
> Do not include `.github` directory into released gem

- .github/workflows/ubuntu.yml
https://github.com/ruby/rake/pull/335 dropped `jruby-head` because ruby/setup-ruby didn't support it.
Now, ruby/setup-ruby supports `jruby-head`, so let's add it back.
> Test with jruby-head

- test/test_rake_clean.rb
Historically, FileUtils logged verbose output to stderr instead of
stdout.  This was fixed in FileUtils to log verbose output to
stdout (since it isn't an error).  This commit adjusts the tests to
handle both FileUtils versions.
> Fix tests to work with current FileUtils

- README.rdoc
In the Readme the links to the Avdi Grimm's rake series articles (https://github.com/ruby/rake#label-Presentations+and+Articles+about+Rake) are currently broken. This PR simply updates the readme to include the valid links.
> Update broken links to rake articles from Avdi in README

- lib/rake/testtask.rb
- test/test_rake_test_task.rb
Unless I'm missing something, we can require `rake_test_loader` directly. It's also safer, because there's no chance of requiring the file of a different copy of `rake`, and faster.
> Simplify default rake test loader

- README.rdoc
except www.a-a-p.org still cannot....
> Update rdoc; HTTP -> HTTPS

- lib/rake/testtask.rb
- test/test_rake_test_task.rb
Due to #357, execution order on Rake 13.0.2 changes from Rake 13.0.1.
Example:
```ruby
Rake::TestTask do |t|
t.test_files = [
"test/a.rb",
"test/b.rb",
]
end
```
On 13.0.2, Rake executes test/b.rb before test/a.rb because test/a.rb are loaded before rake_test_loader.rb.
rake_test_loader.rb executes the Ruby code in ARGV using Kernel.#require, but does not execute test/a.rb which is already loaded.
In addition, Rake 13.0.1 allows specifying test_files without .rb but 13.0.2 doesn't allows.
This commit also fixes this problem.
```ruby
Rake::TestTask do |t|
t.test_files = [
"test/setup",
"test/a.rb",
]
end
```
> Fix breaking change of execution order on TestTask

- .github/workflows/macos.yml
- .github/workflows/windows.yml
This PR uses the quoting from the test.yml in the other YAML files for CI.
> CI: use "3.0" to avoid YAML float conversions

- lib/rake/rake_test_loader.rb
I don't think this require is necessary, and it causes issues if you use the default loader in combination with the `--disable-gems` flag. I guess this could potentially break something is somebody is using the `Rake` constant directly in their tests without requiring `rake`. That should be very rare and easily fixable by requiring it.
> Remove unnecessary require

- lib/rake/thread_pool.rb
This file seems required by `rake` by default. By lazily loading `set`, usages of `rake` that don't use this part of `rake`, don't unnecessarily activate the `set` gem.
This seems really minor, I know. But when testing rubygems & bundler, it's interesting for us to be in full control of the gems that are
loaded, to make sure that we don't unintentionally activate gems causing our users to be unable to select the version of those gems that they need.
> Lazily load `set`

- lib/rake/task_manager.rb
- test/test_rake_rules.rb
rules presently expect string names as their prereqs (among others:
Procs/Methods, RegExp patterns, or pathmap specs)
This adds the conventional ability for a prereq task to be specified
using a Symbol as is common with non-file-based tasks.
closes #349
> rule learns to accept Symbols as a prereq name

- lib/rake/rake_test_loader.rb
- test/test_rake_rake_test_loader.rb
I got a bug report in bundler where the end user error being printed was like this:
```
$ bundle exec rake test
File does not exist: pry
rake aborted!
Command failed with status (1)
/home/deivid/Code/ruby/rake/exe/rake:27:in `<top (required)>'
/home/deivid/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/deivid/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```
This error is very unhelpful about what's going on.
After debugging, I found that rake was swallowing useful information about the error, and also incorrectly stating that a file named "pry" was missing.
This changeset should fix the problem and now `rake` gives more useful information:
```
$ bundle exec rake test
Traceback (most recent call last):
11: from …
```
> Fix rake test loader swallowing useful error information

- lib/rake/file_task.rb
I’m assuming that no benchmarking will be required for the claim “fewer I/O syscall means better performance”.
This may only seem like a trivial improvement for smaller projects. However, I’m dealing with about 22 000 files, and removing <del>this one</del> <ins>these two</ins> system call<ins>s</ins> cut my no-changes build time by <del>14,8 %</del> <ins>12,4 %</ins> on a fast M.2 SSD.
> (Performance) Remove unnecessary I/O syscalls for FileTasks

- .rubocop.yml
- Gemfile
- lib/rake/task.rb
- test/test_rake_clean.rb
- test/test_rake_file_list.rb
- test/test_rake_task.rb
- test/test_rake_test_task.rb
- Pin rubocop to 0.81.0 to keep [TargetRubyVersion: 2.3](https://github.com/ruby/rake/blob/881416e322d597e47e62935ef6a9dbaed934fbfc/.rubocop.yml#L2)
- Update `.rubocop.yml`:
- Rename `Metrics/LineLength` to `Layout/LineLength` ([0.78.0](https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md#0780-2019-12-18))
- Remove `Style/BracesAroundHashParameters` cop` ([0.80.0](https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md#0800-2020-02-18))
- Rename `Layout/TrailingBlankLines` to `Layout/TrailingEmptyLines` (older version...)
> Apply RuboCop linting for Ruby 2.3

- .rubocop.yml
- Gemfile
- Pin rubocop to 1.12.x to bump `TargetRubyVersion` from 2.3 to 2.4
- Update `.rubocop.yml` config
- cf. https://github.com/rubocop/rubocop/blob/master/CHANGELOG.md#0820-2020-04-16
Blocked by #423
> Update rubocop to work with Ruby 2.4 compatible

- .github/workflows/test.yml
Workflow names at https://github.com/ruby/rake/actions should be clear.
> Use 'test' as workflow name on Actions

- .github/workflows/lint.yml
- .rubocop.yml
Just to avoid drifts such as ones fixed in #423.
> Add RuboCop job to Actions

- lib/rake/thread_pool.rb
Lazily requiring it in this matter can break rake whenever
a rake task limits access to the file system.  For example:
```ruby
task :default do
Dir.chroot Dir.pwd
end
```
One reason to lazily require this is to save on memory, but
since Rake::Application appears to always use a thread pool
(Rake::Application#run -> top_level -> run_with_threads ->
thread_pool), it doesn't looks like lazily requiring actually
saves memory in this case.
> Eagerly require set in thread_pool.rb

- lib/rake/application.rb
If the thread_pool does not already exist, there is no point in
creating a thread pool just to join the threads in it.
This is an alternative fix for #440.
> Avoid creating an unnecessary thread pool

- lib/rake/file_utils.rb
- test/test_rake_file_utils.rb
CASE
`FileUtils#sh` truncates (to 42 characters) the echoing of failed shelled-out commands (as determined by their exit status). (BTW, even when the output is redirected to a file, it still truncates, in the same way.)
This isn't about shelled-out commands that _succeed_.
Why truncate the failed ones, anyhow? (And why to 42 characters?) What's the reason or rationale?
Every user wants to know (presumably) exactly which failed command their program was unable to handle, in order to obtain help to make their program work.
Passing a block to `FileUtils#sh` can avoid echoing any failed command, easily. So, any wish to provide some facility to avoid excessive echoing doesn't fully seem to justify this truncation.
This truncation of failed commands seems devoid of test coverage (because, if I …
> Sh fully echoes commands which error exit

- test/test_rake_file_utils.rb
Introduced after #147, which was not fully rebased when it was merged.
> Correct RuboCop offenses

- .github/workflows/test.yml
It was released just recently on december 25th and the test suite does not show
any needed changes, so it should be added to the test matrix.
> Add ruby 3.2 to test matrix

- .github/workflows/dependabot_automerge.yml
* Use `pull_request_target`
* https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
* Apply single step.
* Removed needless feature.
> Rewrite auto-merge feature for dependabot

- lib/rake/application.rb
> Fix grammar in help text

- lib/rake/application.rb
- test/test_rake_application.rb
The `Exception#detailed_message` method was added in Ruby v3.2.0 and is used by the [error_highlight](https://github.com/ruby/error_highlight) gem and others.
https://bugs.ruby-lang.org/issues/18564
However, on the rake task, this benefit is not available due to the use of `Exception#message`.
I propose that the `detailed_message` method call if it can be called.
ruby v3.2.1
Rakefile
```
task :demo do
p self.opject_id
end
```
before
```
$ bundle exec rake demo
rake aborted!
NoMethodError: undefined method `opject_id' for main:Object
/Users/ksss/src/github.com/ksss/rake/Rakefile:35:in `block in <top (required)>'
/Users/ksss/src/github.com/ksss/rake/exe/rake:27:in `<top (required)>'
/Users/ksss/.rbenv/versions/3.2.1/bin/bundle:25:in `load'
/Users/ksss/.rbenv/versions/3.2.1/bin/bundle:25:in …
```
> Support `#detailed_message` when task failed

- lib/rake/application.rb
If the rake task terminates with some error, starting a postmortem session with the debug gem will start in the rescue block of `Rake::Application#standard_exception_handling`, making debugging is difficult.
Rakefile
```
task :demo do
aaa
end
```
```
$ bundle exec rdbg -c -- rake demo
[4, 13] in ~/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bin/rake
4| #
5| # The application 'rake' is installed as part of a gem, and
6| # this file is here to facilitate running it.
7| #
8|
=>   9| require 'rubygems'
10|
11| Gem.use_gemdeps
12|
13| version = ">= 0.a"
=>#0	<main> at ~/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bin/rake:9
(rdbg) config set postmortem true    # command
postmortem = true                  # CONTROL: Enable postmortem debug (default: false)
(rdbg) c    # continue command
rake …
```
> Debug at stop when task fail

- lib/rake/dsl_definition.rb
.c -> .o requires the -c flag. This could be confusing.
> Fix rule example to be correct

- .github/workflows/coverage.yml
- .github/workflows/test.yml
- Gemfile
- test/helper.rb
- test/test_rake_application.rb
- test/test_rake_application_options.rb
- test/test_rake_backtrace.rb
- test/test_rake_clean.rb
- test/test_rake_cpu_counter.rb
- test/test_rake_file_list.rb
- test/test_rake_file_utils.rb
- test/test_rake_functional.rb
- test/test_rake_rake_test_loader.rb
- test/test_rake_task.rb
- test/test_rake_task_with_arguments.rb
- test/test_rake_top_level_functions.rb
- test/test_rake_win32.rb
- test/test_thread_history_display.rb
We used `test-unit` in default gems and bundled gems without `rake`. I would like to reduce dev dependencies from bundled gems.
> Switch to use test-unit

- lib/rake.rb
- lib/rake/application.rb
I will migrate `osturct` as bundled gems at Ruby 3.5. We should remove its dependency from Rake.
> Use Struct instead of OpenStruct.

- lib/rake/dsl_definition.rb
- test/test_rake_directory_task.rb
> Accept FileList object as directory task's target

- lib/rake/application.rb
Fixing:
```
C:/Ruby32-x64/lib/ruby/gems/3.2.0+3/gems/rake-13.0.6/lib/rake/backtrace.rb:21:in `collapse': undefined method `reject' for nil:NilClass (NoMethodError)
backtrace.reject { |elem| elem =~ pattern }
^^^^^^^
from C:/Ruby32-x64/lib/ruby/gems/3.2.0+3/gems/rake-13.0.6/lib/rake/application.rb:249:in `display_exception_backtrace'
from C:/Ruby32-x64/lib/ruby/gems/3.2.0+3/gems/rake-13.0.6/lib/rake/application.rb:218:in `display_exception_details'
from C:/Ruby32-x64/lib/ruby/gems/3.2.0+3/gems/rake-13.0.6/lib/rake/application.rb:226:in `display_cause_details'
from C:/Ruby32-x64/lib/ruby/gems/3.2.0+3/gems/rake-13.0.6/lib/rake/application.rb:219:in `display_exception_details'
from C:/Ruby32-x64/lib/ruby/gems/3.2.0+3/gems/rake-13.0.6/lib/rake/application.rb:208:in `display_error_message'
from …
```
> Fix exception when exception has nil backtrace

- .github/workflows/test.yml
TruffleRuby was removed in #497 but the issues were fixed in current release TruffleRuby 24.0.
> Add TruffleRuby on CI

- History.rdoc
Seems like all the changes are correctly logged in Releases tab of github
I've copied them to history.rdoc since this file is used in gemspec as main source of changes:
https://github.com/ruby/rake/blob/master/rake.gemspec#L28
This will fix empty message for tools like `dependabot` while updating rake
> Add missing changelog

- rake.gemspec
The current link points to a file that hasn't been updated since v13.0.6. The github.com releases link looks to be a more reliable target.
> Provide a 'Changelog' link on rubygems.org/gems/rake

- lib/rake/cpu_counter.rb
This gem is being bundled in Ruby 3.5: https://github.com/ruby/ruby/commit/f365bef0c78085b7db9b6736ae59c1657baa79a3
So, just use buildin commands to do the same thing.
The powershell version will work on at least Windows 8 (from 2012). There are no docs I could find for earlier versions, so it might work on even earlier versions.  https://learn.microsoft.com/en-us/powershell/scripting/install/powershell-support-lifecycle?view=powershell-7.4. Fall back to the deprecated wmic if it doesn't exist.
I have openen https://github.com/grosser/parallel/pull/346 and https://github.com/ruby-concurrency/concurrent-ruby/pull/1051 which do the same thing.
> Remove dependency on `win32ole`

- test/helper.rb
- test/support/rakefile_definitions.rb
- test/test_rake_application_options.rb
- test/test_rake_definitions.rb
- test/test_rake_file_list.rb
- test/test_rake_file_task.rb
- test/test_rake_file_utils.rb
- test/test_rake_makefile_loader.rb
... by consistently using [`File::write`](https://ruby-doc.org/3.3.5/IO.html#method-c-write) instead of [`Kernel#open`](https://ruby-doc.org/3.3.5/Kernel.html#method-i-open).
At the moment, most temporary files (in tests) are written using `Kernel#open` even though sometimes `File::write` is already being used;  this PR refactors all tests to consistently use `File::write`.
It's possibly a matter of style/preference/opinion, but this also makes things slightly more readable and slightly less convoluted; either way, I think `File.write` is a tad more "intention revealing" than `Kernel#open` as well: we are "writing a (Rake-)file" as opposed to "opening a file for writing" ... small but subtle difference. :sweat_smile:
In addition, the content of temporary files is  refactored to …
> chore: refactor how temporary files are created (in tests)

- lib/rake/application.rb
tl;dr - replace`$"` with the equivalent - but much more descriptive - `$LOADED_FEATURES` Ruby built-in ... and work around an apparent parsing bug in "universal" `ctags` while we're at it _(see details below)_
Thanks @hsbt :pray:
---
I noticed that quite a few methods defined in [`lib/rake/application.rb`](https://github.com/ruby/rake/blob/master/lib/rake/application.rb) were missing from a `tags` file generated by the latest version of "universal" [`ctags`](https://github.com/universal-ctags/ctags).
On closer examination, it turns out that all methods defined <ins>after</ins> the `rake_require` method _(defined [here](https://github.com/ruby/rake/blob/master/lib/rake/application.rb#L694) in the Ruby source file)_ don't get indexed by `ctags`:
```ruby
def rake_require(file_name, …
```
> refactor: use `$LOADED_FEATURES` built-in instead of `$"`

- test/helper.rb
- test/test_rake_application.rb
It is very unclear why the [`Rake::TestCase#rake_system_dir`](https://github.com/ruby/rake/blob/master/test/helper.rb#L93-L105) helper method:
```ruby
def rake_system_dir
@system_dir = "system"
FileUtils.mkdir_p @system_dir
File.write File.join(@system_dir, "sys1.rake"), <<~SYS
task "sys1" do
puts "SYS1"
end
SYS
ENV["RAKE_SYSTEM"] = @system_dir
end
```
... creates and sets a `@system_dir` instance variable. :thinking:
On  inspection, it turns out its only use is [the following assertion](https://github.com/ruby/rake/blob/master/test/test_rake_application.rb#L341) in one of the test cases:
```ruby
assert_equal @system_dir, @app.system_dir
```
... so this PR removes the ivar and hardcodes the expected `"system"` value in the assertion:
```diff
-    assert_equal @system_dir, @app.system_dir …
```
> refactor: remove "exposed" `@system_dir` instance variable (in helper method)

- lib/rake/application.rb
Due to it being a tad convoluted, it took me longer than it probably should have to grok what the `Rake::Application#system_dir` method was trying to do.
I think this simplification makes it a lot more obvious, especially as the same ...
```ruby
hash[:lookup_key] || :default_value
```
... idiom is already used elsewhere in the `rake` codebase.
It also avoids a double hash lookup: one lookup to see if `RAKE_SYSTEM` is set in the `ENV` hash, and - if it is - exactly the same lookup again to actually fetch its value. 🎉 
PS - I was tempted to also include the following change in this PR ... happy to take your steer @hsbt : include it in this one, or issue a separate PR instead? (or else forget about it altogether if it's totally bonkers?) 😅 
```diff
--- a/lib/rake/application.rb
+++ …
```
> refactor: simplify `Rake::Application#system_dir` method

- lib/rake/task_manager.rb
I found an unused argument and removed it.
It looks like a leftover from [this commit](https://github.com/ruby/rake/commit/72bdd5d14f34ffdc7a26e4438690cd91b04d2d33#diff-a6c0e245bb30f1b0fc461a5c9b896f91d50498046437742ac114ba2ce21a6c79L293-R292).
> Remove unused argument

- Gemfile
By simply using the latest RDoc release, we can immediately improve https://ruby.github.io/rake's user experience:
> Use latest RDoc release instead of Ruby 3.2's default version

- lib/rake/application.rb
Hot on the heels of the changes in #591, this PR proposes a further simplification of `Rake::Application.standard_system_dir()` by using `Dir.home()` instead of `File.expand_path("~")`
As discussed here:
https://bugs.ruby-lang.org/issues/1027
... this is a much more idiomatic way to determine the home directory of the current user, and has been part of Ruby [since 2009](https://github.com/ruby/ruby/commit/043f665274006e4f040e681e0a1aee4975cf30b5) (`ruby 1.9.2`).
Thanks, @hsbt! :pray:
> refactor: use `Dir.home` to find `rake`'s standard system dir

- lib/rake/task_arguments.rb
- test/test_rake_task_arguments.rb
Implement `Rake::TaskArguments#deconstruct_keys`. This means in an idiomatic ruby 3.x rake task we can use rightward assignment to say:
```
task :get, %i[tenant id] do |_t, args|
args => {tenant:, id:}
...
end
```
... and omit the `.to_h` from `args`, raising `NoMatchingPatternError` if either of the two params is absent from the task args.
> Pattern matching support for arguments

- lib/rake/thread_pool.rb
Since threads count is already guaranteed to be less or equal than max_active_threads in thread_pool.rb:line 113, there is no need to double check.
Not to mention that this will cause a race condition on the JRuby platform, as noted in 5ac9df09d6be3fbb7edb127f31aa0684db620cd3.
Removing the conditional check will also reduce lock acquisitions and improve overall efficiency.
In the original commit 173745949fa299d20a558c0511c02991f056933d, this check was essential. However, after subsequent changes, it seems no one performed a careful review of this logic.
> Remove useless condition check

- doc/command_line_usage.rdoc
> Added document for RAKEOPT

- .github/workflows/dependabot_automerge.yml
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
> Fixed wrong name of environmental variable

- rake.gemspec
Currently, each rake gem release's `source_code_uri` points to its "releases" page URL on GitHub, e.g. https://github.com/ruby/rake/releases/v13.3.0 but that's not indeed a source_code_uri.
Instead, let's simply link_to `https://github.com/ruby/rake`. That's what the `bundle gem` template suggests:
https://github.com/rubygems/rubygems/blob/fcb672f/bundler/lib/bundler/cli/gem.rb#L54
and almost all documentations and test data in rubygems/bundler look like. https://github.com/search?q=repo%3Arubygems%2Frubygems%20source_code_uri&type=code
Or, IMO the name "source code URI" implies that it should at least return a URL that can be `git clone`d.
FYI the configuration was introduced via #328 but there wasn't any detailed discussion about the validity of the value.
> Set source_code_uri metadata to this gem's public repo URL
